### ISSUE TITLE
Can't get it to work on Ubuntu 14.4

### ISSUE THREAD

**Issue by rueckstiess** [imlucas/mongodb-version-manager#13]
It installs fine and all paths are set, but it just doesn't do anything. 

```
tengen@ubuntu:~$ m
tengen@ubuntu:~$ m 2.6.6
tengen@ubuntu:~$
tengen@ubuntu:~$ m --help
tengen@ubuntu:~$ m use 2.6.6
tengen@ubuntu:~$
```

**Comment by imlucas** [comment]
Try turning on debugging:

`DEBUG=* m 2.6.6`

**Comment by imlucas** [comment]
@rueckstiess bump.  Any luck reproducing this with DEBUG on?

**Comment by imlucas** [comment]
chatted offline.  new related fixes coming.  if we can get more diagnostic, let's reopen
